-- ============================================================
-- INERAM - Firmas al pie de la planilla
-- Los nombres de las firmas del reporte salen de esta tabla:
--   - por persona  (persona_id): nombre de la persona asignada
--   - por cargo    (cargo_id)  : cada personal ACTIVO con ese cargo
--   - nombre fijo  (nombre_fijo): texto directo (fallback)
-- La firma es INDEPENDIENTE de las unidades seleccionadas en el
-- reporte (ej. "Jefa de Sala V y Urgencias Pediátricas" firma
-- aún cuando el reporte se imprima de una sola unidad).
-- ============================================================

create table if not exists public.firmas_planilla (
  id          bigint generated by default as identity primary key,
  clave       text not null unique,             -- jefe_unidad / jefe_enfermeria / jefe_personal
  subtitulo   text not null default '',         -- texto bajo el nombre
  cargo_id    bigint references public.cargos(id) on delete set null,
  persona_id  bigint references public.personas(id) on delete set null,
  nombre_fijo text,                             -- nombre manual si no hay persona/cargo
  orden       bigint not null default 0,
  activo      boolean not null default true,
  updated_at  timestamptz not null default now()
);

-- Seed: misma salida que la antigua config (config.FIRMAS).
insert into public.firmas_planilla (clave, subtitulo, nombre_fijo, orden) values
  ('jefe_unidad',     'Jefa de Sala V y Urgencias Pediátricas', 'Lic. De los Angeles Sanchez', 1),
  ('jefe_enfermeria', 'Jefa Dpto. de Enfermería',               'Lic. Laura Gonzalez',          2),
  ('jefe_personal',   'Jefe Dpto. de Personal',                 'Abog. Bernardino Sanabria',    3)
on conflict (clave) do nothing;

-- RLS: solo lectura para autenticados; escritura SOLO vía backend
-- (service_role bypasea el RLS). La app móvil no usa esta tabla.
alter table public.firmas_planilla enable row level security;

drop policy if exists "firmas.read" on public.firmas_planilla;
create policy "firmas.read" on public.firmas_planilla
  for select to authenticated
  using (es_admin() or es_jefe_enfermeria() or es_jefe());

-- ---------- Permisos PostgREST (idempotentes, ver roles.sql) ----------
grant usage on schema public to anon, authenticated, service_role;
grant all privileges on all tables in schema public to anon, authenticated, service_role;
grant all privileges on all sequences in schema public to anon, authenticated, service_role;
alter default privileges in schema public grant all on tables to anon, authenticated, service_role;
alter default privileges in schema public grant all on sequences to anon, authenticated, service_role;