-- ============================================================
-- INERAM - Planilla de Guardia de Enfermería
-- Esquema inicial de Supabase (PostgreSQL)
-- Ejecutar en el SQL Editor del proyecto, o como migración.
-- ============================================================

-- ---------- Catálogos ----------

create table public.unidades (
  id       bigint generated by default as identity primary key,
  nombre   text not null unique,
  activo   boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.sectores (
  id        bigint generated by default as identity primary key,
  unidad_id bigint not null references public.unidades(id) on delete cascade,
  nombre    text not null,
  activo    boolean not null default true,
  created_at timestamptz not null default now(),
  unique (unidad_id, nombre)
);

create table public.cargos (
  id        bigint generated by default as identity primary key,
  nombre    text not null unique,
  activo    boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.turnos (
  id           bigint generated by default as identity primary key,
  codigo       text not null unique,          -- M, T, N1, N2, N3, D
  descripcion  text,
  hora_inicio  time not null,
  hora_fin     time not null,
  activo       boolean not null default true,
  created_at   timestamptz not null default now()
);

-- ---------- Personal ----------

create table public.personas (
  id            bigint generated by default as identity primary key,
  idpersonal_legacy text,                     -- id de AppSheet conservado del histórico
  nombre        text not null,
  ci            text,
  registro      text,
  unidad_id     bigint references public.unidades(id),
  sector_id     bigint references public.sectores(id),
  cargo_id      bigint references public.cargos(id),
  turno_id      bigint references public.turnos(id),
  estado        text not null default 'ACTIVO' check (estado in ('ACTIVO', 'INACTIVO')),
  orden         bigint not null default 0,    -- posición en la planilla impresa (por grupo)
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index idx_personas_unidad_sector_orden
  on public.personas (unidad_id, sector_id, orden, nombre);

-- ---------- Ausencias (histórico y en curso) ----------

create table public.vacaciones (
  id           bigint generated by default as identity primary key,
  persona_id   bigint not null references public.personas(id) on delete cascade,
  fecha_inicio date not null,
  fecha_fin    date not null,
  observacion  text,
  created_at   timestamptz not null default now(),
  constraint chk_vacaciones_rango check (fecha_fin >= fecha_inicio)
);

create index idx_vacaciones_persona on public.vacaciones (persona_id, fecha_inicio);

create table public.libres (
  id           bigint generated by default as identity primary key,
  persona_id   bigint not null references public.personas(id) on delete cascade,
  fecha_inicio date not null,
  fecha_fin    date not null,
  motivo       text,
  created_at   timestamptz not null default now(),
  constraint chk_libres_rango check (fecha_fin >= fecha_inicio)
);

create index idx_libres_persona on public.libres (persona_id, fecha_inicio);

-- ---------- Plan mensual (mes a planificar) ----------

create table public.plan_mensual (
  id         bigint generated by default as identity primary key,
  persona_id bigint not null references public.personas(id) on delete cascade,
  fecha      date not null,
  turno_id   bigint not null references public.turnos(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_plan_persona_fecha unique (persona_id, fecha)
);

create index idx_plan_fecha on public.plan_mensual (fecha);

-- ---------- Perfiles / roles ----------

create table public.perfiles (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references auth.users(id) on delete cascade,
  rol        text not null default 'jefe' check (rol in ('jefe')),
  unidad_id  bigint references public.unidades(id),
  created_at timestamptz not null default now(),
  unique (user_id)
);

-- Indica si el usuario autenticado es jef@ de unidad.
create or replace function public.es_jefe()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.perfiles p
    where p.user_id = auth.uid()
      and p.rol = 'jefe'
  );
$$;

-- Alta automática de perfil al crear un usuario en Supabase Auth.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.perfiles (user_id, rol)
  values (new.id, 'jefe');
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------- RLS ----------

alter table public.unidades    enable row level security;
alter table public.sectores    enable row level security;
alter table public.cargos      enable row level security;
alter table public.turnos      enable row level security;
alter table public.personas    enable row level security;
alter table public.vacaciones  enable row level security;
alter table public.libres      enable row level security;
alter table public.plan_mensual enable row level security;
alter table public.perfiles    enable row level security;

-- Solo jefes pueden ver/escribir la operación.
create policy "jefes gestionan unidades"    on public.unidades    for all to authenticated using (public.es_jefe()) with check (public.es_jefe());
create policy "jefes gestionan sectores"    on public.sectores    for all to authenticated using (public.es_jefe()) with check (public.es_jefe());
create policy "jefes gestionan cargos"      on public.cargos      for all to authenticated using (public.es_jefe()) with check (public.es_jefe());
create policy "jefes gestionan turnos"      on public.turnos      for all to authenticated using (public.es_jefe()) with check (public.es_jefe());
create policy "jefes gestionan personal"    on public.personas    for all to authenticated using (public.es_jefe()) with check (public.es_jefe());
create policy "jefes gestionan vacaciones"  on public.vacaciones  for all to authenticated using (public.es_jefe()) with check (public.es_jefe());
create policy "jefes gestionan libres"      on public.libres      for all to authenticated using (public.es_jefe()) with check (public.es_jefe());
create policy "jefes gestionan plan"        on public.plan_mensual for all to authenticated using (public.es_jefe()) with check (public.es_jefe());

-- Cada usuario solo ve su propio perfil.
create policy "perfil propio" on public.perfiles
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- ---------- Seed de catálogos (datos reales de la hoja) ----------

insert into public.unidades (nombre) values ('URGENCIAS'), ('SALA V');

insert into public.sectores (unidad_id, nombre)
select u.id, s.nombre
from public.unidades u,
     (values ('URGENCIAS', 'RAC'),
             ('URGENCIAS', 'INTERNADOS'),
             ('SALA V',    'SALA')) as s(unidad, nombre)
where u.nombre = s.unidad;

insert into public.cargos (nombre) values ('RT'), ('JEFATURA'), ('AUXILIAR');

insert into public.turnos (codigo, descripcion, hora_inicio, hora_fin) values
  ('M',  'Mañana',       '06:00', '12:00'),
  ('T',  'Tarde',        '12:00', '18:00'),
  ('N1', 'Noche 1',      '18:00', '06:00'),
  ('N2', 'Noche 2',      '18:00', '06:00'),
  ('N3', 'Noche 3',      '18:00', '06:00'),
  ('D',  'Fin de semana','06:00', '18:00');